# Generated by Django 5.0.1 on 2024-02-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Onl', 'Online'), ('Ofl', 'Ofline'), ('Ban', 'Banned')], max_length=3)),
            ],
        ),
    ]
